#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
Name tables for Final Fantasy IX save data: items, support abilities, and
Tetra Master card types, indexed by their in-save byte ID.

Transcribed from the string tables embedded in Gjoerulv's "Memoria" FF9 save
editor (game text data, not the tool's own source code); see NOTICES.md.
"""
from __future__ import annotations

ITEM_NAMES = [
    'Hammer',
    'Dagger',
    'Mage Masher',
    'Mythril Dagger',
    'Gladius',
    'Zorlin Shape',
    'Orichalcon',
    'Butterfly Sword',
    'The Ogre',
    'Exploda',
    'Rune Thoot',
    'Angel Bless',
    'Sargatanas',
    'Masamune',
    'The Tower',
    'Ultima Weapon',
    'Broadsword',
    'Iron Sword',
    'Mythril Sword',
    'Blood Sword',
    'Ice Brand',
    'Coral Sword',
    'Diamond Sword',
    'Flame Saber',
    'Rune Blade',
    'Defender',
    'Save The Queen',
    'UltimaSword',
    'Excalibur',
    'Ragnarok',
    'Excalibur II',
    'Javelin',
    'Mythril Spear',
    'Partisan',
    'Ice Lance',
    'Trident',
    'Heavy Lance',
    'Obelisk',
    'Holy Lance',
    "Kain's Lance",
    "Dragon's Hair",
    "Cat's Claws",
    'Poison Knuckles',
    'Mythril Knuckles',
    'Scissor Fangs',
    "Dragon's Claws",
    'Tiger Fangs',
    'Avenger',
    'Kaiser Knuckles',
    'Duel Claws',
    'Rune Claws',
    'Air Racket',
    'Multina Racket',
    'Magic Racket',
    'Mythril Racket',
    "Priest's Racket",
    'Tiger Racket',
    'Rod',
    'Mythril Rod',
    'Stardust Rod',
    'Healing Rod',
    "Asura's Rod",
    'Wizard Rod',
    'Whale Whisker',
    "Golem's Flute",
    "Lamia's Flute",
    'Fairy Flute',
    'Hamelin',
    "Siren's Flute",
    'Angel Flute',
    'Mage Staff',
    'Flame Staff',
    'Ice Staff',
    'Lightning Staff',
    'Oak Staff',
    'Cypress Pile',
    'Octagon Rod',
    'High Mage Staff',
    'Mace of Zeus',
    'Fork',
    'Needle Fork',
    'Mythril Fork',
    'Silver Fork',
    'Bistro Fork',
    'Gastro Fork',
    'Pinwheel',
    'Rising Sun',
    'Wing Edge',
    'Wrist',
    'Leather Wrist',
    'Glass Armlet',
    'Bone Wrist',
    'Mythril Armlet',
    'Magic Armlet',
    'Chimera Armlet',
    "Egoist's Armlet",
    'N-Kai Armlet',
    'Jade Armlet',
    'Thief Gloves',
    'Dragon Wrist',
    'Power Wrist',
    'Bracer',
    'Bronze Gloves',
    'Silver Gloves',
    'Mythril Gloves',
    'Thunder Gloves',
    'Diamond Gloves',
    'Venitia Shield',
    'Defense Gloves',
    'Genji Gloves',
    'Aegis Gloves',
    'Gauntlets',
    'Leather Hat',
    'Straw Hat',
    'Feather Hat',
    'Steepled Hat',
    'Headgear',
    'Magus Hat',
    'Bandana',
    "Mage's Hat",
    "Lamia's Tiara",
    'Ritual Hat',
    'Twist Headband',
    'Mantra Band',
    'Dark Hat',
    'Green Beret',
    'Black Hood',
    'Red Hat',
    'Golden Heirpin',
    'Coronet',
    'Flash Hat',
    'Adaman Hat',
    'Theif Hat',
    'Holy Miter',
    'Golden Skullcap',
    'Circlet',
    'Rubber Helm',
    'Bronze Helm',
    'Iron Helm',
    'Barbut',
    'Mythril Helm',
    'Gold Helm',
    'Cross Helm',
    'Diamond Helm',
    'Platinum Helm',
    'Kaiser Helm',
    'Genji Helm',
    'Grand Helm',
    'Aloha T-shirt',
    'Leather Shirt',
    'Silk Shirt',
    'Leather Plate',
    'Bronze Vest',
    'Chain Plate',
    'Mythril Vest',
    'Adaman Vest',
    'Magician Cloak',
    'Survival Vest',
    'Brigandine',
    'Judo Uniform',
    'Power Vest',
    'Gaia Gear',
    "Demon's Vest",
    "Minerva's Plate",
    'Ninja Gear',
    'Dark Gear',
    'Rubber Suit',
    'Brave Suit',
    'Cotton Robe',
    'Silk Robe',
    'Magician Robe',
    "Glutton's Robe",
    'White Robe',
    'Black Robe',
    'Light Robe',
    'Robe of Lords',
    'Tin Armor',
    'Bronze Armor',
    'Linen Cuirass',
    'Chain Mail',
    'Mythril Armor',
    'Plate Mail',
    'Gold Armor',
    'Shield Armor',
    "Demon's Mail",
    'Diamon Armor',
    'Platina Armor',
    'Carabini Mail',
    'Dragon Mail',
    'Genji Armor',
    'Maximilian',
    'Grand Armor',
    'Desert Boots',
    'Magician Shoes',
    'Germinas Boots',
    'Sandals',
    'Feather Boots',
    'Battle Boots',
    'Running Shoes',
    'Anklet',
    'Power Belt',
    'Black Belt',
    'Glass Buckle',
    "Madain's Ring",
    'Rosetta Ring',
    'Reflact Ring',
    'Coral Ring',
    'Promist Ring',
    'Rebirth Ring',
    'Protect Ring',
    'Pumice Piece',
    'Pumice',
    'Yellow Scarf',
    'Gold Choker',
    'Fairy Earrings',
    'Angel Earrings',
    'Pearl Rouge',
    'Pearl Armlet',
    'Cachusha',
    'Barette',
    'Extension',
    'Ribbon',
    'Maiden Prayer',
    'Ancient Aroma',
    'Garnet',
    'Amethyst',
    'Aquamarine',
    'Diamond',
    'Emerald',
    'Moonstone',
    'Ruby',
    'Peridot',
    'Sapphire',
    'Opal',
    'Topaz',
    'Lapiz Lazuli',
    'Potion',
    'Hi-Potion',
    'Ether',
    'Elixir',
    'Phoenix Down',
    'Echo Screen',
    'Soft',
    'Antidote',
    'Eye Drops',
    'Magic Tag',
    'Vaccine',
    'Remedy',
    'Annoyntment',
    'Phoenix Pinion',
    'Dark Matter',
    'Gysahl Greens',
    'Dead Peper',
    'Tent',
    'Ore',
    'Nothing',
]

SUPPORT_ABILITY_NAMES = [
    'Auto-Reflect',
    'Auto-Float',
    'Auto-Haste',
    'Auto-Regen',
    'Auto-Life',
    'HP+10%',
    'HP+20%',
    'MP+10%',
    'MP+20%',
    'Accuracy+',
    'Distract',
    'Long Reach',
    'MP Attack',
    'Bird Killer',
    'Bug Killer',
    'Stone Killer',
    'Undead Killer',
    'Dragon Killer',
    'Devil Killer',
    'Beast killer',
    'Man Eater',
    'High Jump',
    'Master Thief',
    'Steal Gil',
    'Healer',
    'Add Status',
    'Gamble Defence',
    'Chemist',
    'Power Throw',
    'Power Up',
    'Reflect-Null',
    'Reflectx2',
    'Mag Elem Null',
    'Concentrate',
    'Half MP',
    'High Tide',
    'Counter',
    'Cover',
    'Protect Girls',
    'Eye 4 Eye',
    'Body Temp',
    'Alert',
    'Initiative',
    'Level Up',
    'Ability Up',
    'Millionaire',
    'Flee-Gil',
    'Guardian Mog',
    'Insomniac',
    'Antibody',
    'Bright Eyes',
    'Loudmouth',
    'Restore HP',
    'Jelly',
    'Return Magic',
    'Absorb MP',
    'Auto-Potion',
    'Locomotion',
    'Clear Headed',
    'Boost',
    "Odin's Sword",
    'Mug',
    'Bandit',
    'Void',
]

CARD_TYPE_NAMES = [
    'Goblin',
    'Fang',
    'Skeleton',
    'Flan',
    'Zaghnol',
    'Lizard Man',
    'Zombie',
    'Bomb',
    'Ironite',
    'Sahagin',
    'Yeti',
    'Mimic',
    'Wyerd',
    'Mandragora',
    'Crawler',
    'Sand Scorpion',
    'Nymph',
    'Sand Golem',
    'Zuu',
    'Dragonfly',
    'Carrion Worm',
    'Cerberus',
    'Antlion',
    'Cactuar',
    'Gimme Cat',
    'Ragtimer',
    'Hedgehog Pie',
    'Ralvuimahgo',
    'Ochu',
    'Troll',
    'Blazer Beetle',
    'Abomination',
    'Zemzelett',
    'Stroper',
    'Tantarian',
    'Grand Dragon',
    'Feather Circle',
    'Hecteyes',
    'Ogre',
    'Armstrong',
    'Ash',
    'Wraith',
    'Gargoyle',
    'Vepal',
    'Grimlock',
    'Tonberry',
    'Veteran',
    'Garuda',
    'Malboro',
    'Mover',
    'Abadon',
    'Behemoth',
    'Iron Man',
    'Nova Dragon',
    'Ozma',
    'Hades',
    'Holy',
    'Meteor',
    'Flare',
    'Shiva',
    'Ifrit',
    'Ramuh',
    'Atomos',
    'Odin',
    'Leviathan',
    'Bahamut',
    'Ark',
    'Fenrir',
    'Madeen',
    'Alexander',
    'Excalibur 2',
    'Ultima Weapon',
    'Masamune',
    'Elixir',
    'Dark Matter',
    'Ribbon',
    'Tiger Racket',
    'Save The Queen',
    'Genji',
    'Mythril Sword',
    'Blue Narciss',
    'Hilda Garde 3',
    'Invincible',
    'Cargo Ship',
    'Hilda Garde 1',
    'Red Rose',
    'Theater Ship',
    'Viltgance',
    'Chocobo',
    'Fat Chocobo',
    'Mog',
    'Frog',
    'Oglop',
    'Alexandria',
    'Lindblum',
    'Two Moons',
    'Gargant',
    'Namingway',
    'Boco',
    'Airship',
]


def _build_lookup(names: list[str]) -> dict[str, int]:
    lookup: dict[str, int] = {}
    for idx, name in enumerate(names):
        key = name.strip().lower()
        if key and key not in lookup:
            lookup[key] = idx
    return lookup


ITEM_NAME_TO_ID = _build_lookup(ITEM_NAMES)
SUPPORT_ABILITY_NAME_TO_ID = _build_lookup(SUPPORT_ABILITY_NAMES)
CARD_TYPE_NAME_TO_ID = _build_lookup(CARD_TYPE_NAMES)

EMPTY_ITEM_ID = ITEM_NAMES.index("Nothing")
NO_CARD_TYPE = 0xFF


def item_name(item_id: int) -> str:
    if 0 <= item_id < len(ITEM_NAMES):
        return ITEM_NAMES[item_id]
    return f"0x{item_id:02X}"


def support_ability_name(bit_index: int) -> str:
    if 0 <= bit_index < len(SUPPORT_ABILITY_NAMES):
        return SUPPORT_ABILITY_NAMES[bit_index]
    return f"bit{bit_index}"


def card_type_name(type_id: int) -> str:
    if type_id == NO_CARD_TYPE or not (0 <= type_id < len(CARD_TYPE_NAMES)):
        return "(none)"
    return CARD_TYPE_NAMES[type_id]


def resolve_item_id(token: str) -> int:
    token = token.strip()
    if not token:
        raise ValueError("empty item name/ID")
    try:
        base = 16 if token.lower().startswith("0x") else 10
        value = int(token, base)
    except ValueError:
        value = None
    if value is not None:
        if not (0 <= value <= 0xFF):
            raise ValueError(f"item ID out of range 0-255: {value}")
        return value
    key = token.lower()
    if key in ITEM_NAME_TO_ID:
        return ITEM_NAME_TO_ID[key]
    matches = [n for n in ITEM_NAMES if key in n.lower()]
    if len(matches) == 1:
        return ITEM_NAME_TO_ID[matches[0].lower()]
    if len(matches) > 1:
        raise ValueError(f"ambiguous item name {token!r}: matches {', '.join(matches[:8])}")
    raise ValueError(f"unknown item name/ID: {token!r}")


# PS1-era menu/name font table (char -> byte code), used only by the legacy
# save format; the 2016 Steam/PC/mobile re-release stores names as plain text.
LEGACY_CHAR_TO_BYTE: dict[str, int] = {
    '0': 0x00,
    '1': 0x01,
    '2': 0x02,
    '3': 0x03,
    '4': 0x04,
    '5': 0x05,
    '6': 0x06,
    '7': 0x07,
    '8': 0x08,
    '9': 0x09,
    '+': 0x0A,
    '-': 0x0B,
    '*': 0x0C,
    '=': 0x0D,
    '%': 0x0E,
    ' ': 0x0F,
    'A': 0x10,
    'B': 0x11,
    'C': 0x12,
    'D': 0x13,
    'E': 0x14,
    'F': 0x15,
    'G': 0x16,
    'H': 0x17,
    'I': 0x18,
    'J': 0x19,
    'K': 0x1A,
    'L': 0x1B,
    'M': 0x1C,
    'N': 0x1D,
    'O': 0x1E,
    'P': 0x1F,
    'Q': 0x20,
    'R': 0x21,
    'S': 0x22,
    'T': 0x23,
    'U': 0x24,
    'V': 0x25,
    'W': 0x26,
    'X': 0x27,
    'Y': 0x28,
    'Z': 0x29,
    '(': 0x2A,
    '!': 0x2B,
    '?': 0x2C,
    '“': 0x2D,
    ':': 0x2E,
    '.': 0x2F,
    'a': 0x30,
    'b': 0x31,
    'c': 0x32,
    'd': 0x33,
    'e': 0x34,
    'f': 0x35,
    'g': 0x36,
    'h': 0x37,
    'i': 0x38,
    'j': 0x39,
    'k': 0x3A,
    'l': 0x3B,
    'm': 0x3C,
    'n': 0x3D,
    'o': 0x3E,
    'p': 0x3F,
    'q': 0x40,
    'r': 0x41,
    's': 0x42,
    't': 0x43,
    'u': 0x44,
    'v': 0x45,
    'w': 0x46,
    'x': 0x47,
    'y': 0x48,
    'z': 0x49,
    ')': 0x4A,
    ',': 0x4B,
    '/': 0x4C,
    '•': 0x4D,
    '~': 0x4E,
    '&': 0x4F,
    'Á': 0x50,
    'À': 0x51,
    'Â': 0x52,
    'Ä': 0x53,
    'É': 0x54,
    'È': 0x55,
    'Ê': 0x56,
    'Ë': 0x57,
    'Í': 0x58,
    'Ì': 0x59,
    'Î': 0x5A,
    'Ï': 0x5B,
    'Ó': 0x5C,
    'Ò': 0x5D,
    'Ô': 0x5E,
    'Ö': 0x5F,
    'Ú': 0x60,
    'Ù': 0x61,
    'Û': 0x62,
    'Ü': 0x63,
    'á': 0x64,
    'à': 0x65,
    'â': 0x66,
    'ä': 0x67,
    'é': 0x68,
    'è': 0x69,
    'ê': 0x6A,
    'ë': 0x6B,
    'í': 0x6C,
    'ì': 0x6D,
    'î': 0x6E,
    'ï': 0x6F,
    'ó': 0x70,
    'ò': 0x71,
    'ô': 0x72,
    'ö': 0x73,
    'ú': 0x74,
    'ù': 0x75,
    'û': 0x76,
    'ü': 0x77,
    'Ç': 0x78,
    'Ñ': 0x79,
    'ç': 0x7A,
    'ñ': 0x7B,
    'Œ': 0x7C,
    'ß': 0x7D,
    '’': 0x7E,
    '”': 0x7F,
    '_': 0x80,
    '】': 0x81,
    '【': 0x82,
    '∴': 0x83,
    '∵': 0x84,
    '♪': 0x85,
    '→': 0x86,
    '∈': 0x87,
    'ⅹ': 0x88,
    '♦': 0x89,
    '§': 0x8A,
    '‹': 0x8B,
    '›': 0x8C,
    '←': 0x8D,
    '∋': 0x8E,
    '↑': 0x8F,
    '△': 0x90,
    '□': 0x91,
    '∞': 0x92,
    '♥': 0x93,
    '≪': 0xA1,
    '≫': 0xA2,
    '↓': 0xA3,
    '─': 0xA4,
    '°': 0xA5,
    '★': 0xA6,
    '♂': 0xA7,
    '♀': 0xA8,
    '☺': 0xA9,
    '„': 0xAB,
    '‘': 0xAC,
    '#': 0xAD,
    '※': 0xAE,
    ';': 0xAF,
    '¡': 0xB0,
    '¿': 0xB1,
}
LEGACY_BYTE_TO_CHAR: dict[int, str] = {v: k for k, v in LEGACY_CHAR_TO_BYTE.items()}
LEGACY_NAME_TERMINATOR = 0xFF


def encode_legacy_text(text: str, length: int) -> bytes:
    out = bytearray()
    for ch in text[:length]:
        out.append(LEGACY_CHAR_TO_BYTE.get(ch, LEGACY_CHAR_TO_BYTE['?']))
    while len(out) < length:
        out.append(LEGACY_NAME_TERMINATOR)
    return bytes(out[:length])


def decode_legacy_text(data: bytes) -> str:
    out = []
    for b in data:
        if b == LEGACY_NAME_TERMINATOR:
            break
        ch = LEGACY_BYTE_TO_CHAR.get(b)
        if ch is not None:
            out.append(ch)
    return ''.join(out)
